# Generated by Django 4.1.3 on 2025-03-25 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='test_model',
        ),
    ]
