name: alobooking-dev

on:
  push:
    branches:
      - dev

jobs:
  trigger-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Trigger workflow in other repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEV_PAT }}
          repository: OscarLTC/Alo-Booking
          event-type: merge-trigger-dev
          client-payload: '{"target_branch": "dev"}'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Django (api) to Render (Dev)
        env:
          RENDER_DEV_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL_DEV }}
        run: |
          curl -X POST "$RENDER_DEV_DEPLOY_HOOK_URL"
