name: alobooking-main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build affected apps
        run: npx nx affected:build --base=HEAD~1 --head=HEAD

      - name: Deploy Next.js (web) to Vercel
        run: |
          echo "Deploying Next.js (web) to Vercel..."

      - name: Deploy Django (api) to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL_PROD }}
        run: |
          curl "$DEPLOY_URL"
